# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='date_time',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expires_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 12, 0, 51, 36, 640957, tzinfo=utc)),
        ),
    ]
